user1, 2019-08-14 10:53:35.032254
user1, 2019-08-14 10:55:53.559885
user1, 2019-08-14 10:57:47.230193
user2, 2019-08-16 22:53:08.750204
user2, 2019-08-16 22:54:54.245375
Bill, 2019-08-16 22:56:29.304352
Bill, 2019-08-16 22:57:12.765061
user3, 2019-08-16 22:58:40.589809
user2, 2019-08-16 23:01:54.355371
Bill, 2019-08-16 23:02:19.041352
Bill, 2019-08-16 23:03:25.325061
user3, 2019-08-16 23:05:37.889409
luvo, 2019-08-27 16:13:00.365508
user1, 2019-08-27 18:58:36.835177
user3, 2019-09-03 22:43:03.089699
luvo, 2019-09-04 10:37:19.052698
Internal Server Error: /product/91/
Traceback (most recent call last):
  File "C:\Users\User\djangogirls\myvenv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\User\djangogirls\myvenv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\User\djangogirls\myvenv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\djangogirls\ecommerce\views.py", line 64, in ProductPage
    attr_id = int(request.session['item'])
  File "C:\Users\User\djangogirls\myvenv\lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'item'
luvo, 2019-09-04 21:38:00.170382
luvo, 2019-09-04 21:38:02.055046
Mpumi, 2019-09-05 16:22:01.710157
Forbidden (CSRF token missing or incorrect.): /sign-up/
luvo, 2019-09-05 19:33:26.779973
Internal Server Error: /my-shop/update-product/product/46/
Traceback (most recent call last):
  File "C:\Users\User\djangogirls\myvenv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\User\djangogirls\myvenv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\User\djangogirls\myvenv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\djangogirls\myvenv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\User\djangogirls\myvenv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\User\djangogirls\profiles\views.py", line 206, in UpdateProduct
    ProductInlineformset = inlineformset_factory(Product, ProductImage)
  File "C:\Users\User\djangogirls\myvenv\lib\site-packages\django\forms\models.py", line 1080, in inlineformset_factory
    FormSet = modelformset_factory(model, **kwargs)
  File "C:\Users\User\djangogirls\myvenv\lib\site-packages\django\forms\models.py", line 864, in modelformset_factory
    "Calling modelformset_factory without defining 'fields' or "
django.core.exceptions.ImproperlyConfigured: Calling modelformset_factory without defining 'fields' or 'exclude' explicitly is prohibited.
luvo, 2019-09-05 21:38:07.031577
